In [1]:
#import the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('hepatitis.csv')

In [3]:
df.head()

age     sex steroid  antivirals fatigue malaise anorexia liver_big  \
0   30    male   False       False   False   False    False     False   
1   50  female   False       False    True   False    False     False   
2   78  female    True       False    True   False    False      True   
3   31  female     NaN        True   False   False    False      True   
4   34  female    True       False   False   False    False      True   

  liver_firm spleen_palpable spiders ascites varices  bilirubin  \
0      False           False   False   False   False        1.0   
1      False           False   False   False   False        0.9   
2      False           False   False   False   False        0.7   
3      False           False   False   False   False        0.7   
4      False           False   False   False   False        1.0   

   alk_phosphate   sgot  albumin  protime  histology class  
0           85.0   18.0      4.0      NaN      False  live  
1          135.0   42.0      3.5      NaN      False  live  
2           96.0   32.0      4.0      NaN      False  live  
3           46.0   52.0      4.0     80.0      False  live  
4            NaN  200.0      4.0      NaN      False  live

In [4]:
df['class'].replace({'live':1, 'die':0}, inplace=True)

In [5]:
df.isnull().sum()

age                 0
sex                 0
steroid             1
antivirals          0
fatigue             1
malaise             1
anorexia            1
liver_big          10
liver_firm         11
spleen_palpable     5
spiders             5
ascites             5
varices             5
bilirubin           6
alk_phosphate      29
sgot                4
albumin            16
protime            67
histology           0
class               0
dtype: int64

In [6]:
df.dtypes

age                  int64
sex                 object
steroid             object
antivirals            bool
fatigue             object
malaise             object
anorexia            object
liver_big           object
liver_firm          object
spleen_palpable     object
spiders             object
ascites             object
varices             object
bilirubin          float64
alk_phosphate      float64
sgot               float64
albumin            float64
protime            float64
histology             bool
class                int64
dtype: object

In [7]:
df['steroid'].mode()

0    True
dtype: object

In [8]:
df['steroid'].fillna(df['steroid'].mode().index[0], inplace=True)

In [9]:
df['steroid'].isna().sum()

0

In [10]:
df['fatigue'].fillna(df['fatigue'].mode().index[0], inplace=True)

In [11]:
df['fatigue'].isna().sum()

0

In [12]:
df['malaise'].fillna(df['malaise'].mode().index[0], inplace=True)

In [13]:
df['malaise'].isna().sum()

0

In [14]:
df['anorexia'].fillna(df['anorexia'].mode().index[0], inplace=True)

In [15]:
df['anorexia'].isna().sum()

0

In [16]:
df['liver_big'].fillna(df['liver_big'].mode().index[0], inplace=True)

In [17]:
df['liver_big'].isna().sum()

0

In [18]:
df['liver_firm'].fillna(df['liver_firm'].mode().index[0], inplace=True)

In [19]:
df['spleen_palpable'].fillna(df['spleen_palpable'].mode().index[0], inplace=True)

In [20]:
df['spiders'].fillna(df['spiders'].mode().index[0], inplace=True)

In [21]:
df['ascites'].fillna(df['ascites'].mode().index[0], inplace=True)

In [22]:
df['varices'].fillna(df['varices'].mode().index[0], inplace=True)

In [23]:
df['bilirubin'].fillna(df['bilirubin'].mean(), inplace=True)

In [24]:
df['bilirubin'].isna().sum()

0

In [25]:
df['bilirubin'].fillna(df['bilirubin'].mean(), inplace=True)

In [26]:
df['alk_phosphate'].describe()
#Here the descriptive statistics shows that there is difference between mean and median so i prefer to go on imputation by median

count    126.000000
mean     105.325397
std       51.508109
min       26.000000
25%       74.250000
50%       85.000000
75%      132.250000
max      295.000000
Name: alk_phosphate, dtype: float64

In [27]:
df['alk_phosphate'].fillna(df['alk_phosphate'].median(), inplace=True)

In [28]:
df['alk_phosphate'].isna().sum()

0

In [29]:
df['sgot'].describe()

count    151.00000
mean      85.89404
std       89.65089
min       14.00000
25%       31.50000
50%       58.00000
75%      100.50000
max      648.00000
Name: sgot, dtype: float64

In [30]:
df['sgot'].fillna(df['sgot'].median(), inplace=True)

In [31]:
df['sgot'].isna().sum()

0

In [32]:
df['protime'].describe()
#There is no difference between mean and median, so i want to impute by mean here

count     88.000000
mean      61.852273
std       22.875244
min        0.000000
25%       46.000000
50%       61.000000
75%       76.250000
max      100.000000
Name: protime, dtype: float64

In [33]:
df['protime'].fillna(df['protime'].mean(), inplace=True)

In [34]:
df['protime'].isna().sum()

0

In [ ]:
df.isnull().sum()

In [37]:
df['spleen_palpable'].fillna(df['spleen_palpable'].mode().index[0], inplace=True)

In [38]:
df['spleen_palpable'].isna().sum()

0

In [39]:
df['albumin'].describe()

count    139.000000
mean       3.817266
std        0.651523
min        2.100000
25%        3.400000
50%        4.000000
75%        4.200000
max        6.400000
Name: albumin, dtype: float64

In [40]:
df['albumin'].fillna(df['albumin'].mean(), inplace=True)

In [41]:
df['albumin'].isna().sum()

0

In [42]:
df.isnull().sum().sum()

0

In [43]:
df.head(n=10)

age     sex steroid  antivirals fatigue malaise anorexia liver_big  \
0   30    male   False       False   False   False    False     False   
1   50  female   False       False    True   False    False     False   
2   78  female    True       False    True   False    False      True   
3   31  female       0        True   False   False    False      True   
4   34  female    True       False   False   False    False      True   
5   34  female    True       False   False   False    False      True   
6   51  female   False       False    True   False     True      True   
7   23  female    True       False   False   False    False      True   
8   39  female    True       False    True   False    False      True   
9   30  female    True       False   False   False    False      True   

  liver_firm spleen_palpable spiders ascites varices  bilirubin  \
0      False           False   False   False   False   1.000000   
1      False           False   False   False   False   0.900000   
2      False           False   False   False   False   0.700000   
3      False           False   False   False   False   0.700000   
4      False           False   False   False   False   1.000000   
5      False           False   False   False   False   0.900000   
6      False            True    True   False   False   1.427517   
7      False           False   False   False   False   1.000000   
8       True           False   False   False   False   0.700000   
9      False           False   False   False   False   1.000000   

   alk_phosphate   sgot   albumin    protime  histology  class  
0           85.0   18.0  4.000000  61.852273      False      1  
1          135.0   42.0  3.500000  61.852273      False      1  
2           96.0   32.0  4.000000  61.852273      False      1  
3           46.0   52.0  4.000000  80.000000      False      1  
4           85.0  200.0  4.000000  61.852273      False      1  
5           95.0   28.0  4.000000  75.000000      False      1  
6           85.0   58.0  3.817266  61.852273      False      0  
7           85.0   58.0  3.817266  61.852273      False      1  
8           85.0   48.0  4.400000  61.852273      False      1  
9           85.0  120.0  3.900000  61.852273      False      1

In [44]:
df['steroid'].value_counts()

True     78
False    77
Name: steroid, dtype: int64

In [78]:
df['steroid'].unique()

array([False, True], dtype=object)

In [79]:
df1=df.copy()

In [89]:
df1.head(2)

age  sex steroid antivirals fatigue malaise anorexia liver_big liver_firm  \
0   30    1   False      False   False   False    False     False      False   
1   50    0   False      False    True   False    False     False      False   

  spleen_palpable spiders ascites varices  bilirubin  alk_phosphate  sgot  \
0           False   False   False   False        1.0           85.0  18.0   
1           False   False   False   False        0.9          135.0  42.0   

   albumin    protime  histology  class  
0      4.0  61.852273      False      1  
1      3.5  61.852273      False      1

In [97]:
df1['steroid']=pd.get_dummies(df1['steroid'])

In [98]:
df1['antivirals']=df1['antivirals'].astype(object)

In [99]:
df1['antivirals']=pd.get_dummies(df1['antivirals'])

In [100]:
df1.head(2)

age  sex  steroid  antivirals fatigue malaise anorexia liver_big  \
0   30    1        0           1   False   False    False     False   
1   50    0        0           1    True   False    False     False   

  liver_firm spleen_palpable spiders ascites varices  bilirubin  \
0      False           False   False   False   False        1.0   
1      False           False   False   False   False        0.9   

   alk_phosphate  sgot  albumin    protime  histology  class  
0           85.0  18.0      4.0  61.852273      False      1  
1          135.0  42.0      3.5  61.852273      False      1

In [101]:
df1['histology']=df1['histology'].astype(object)

In [102]:
df1['histology']=pd.get_dummies(df1['histology'])

In [103]:
df1.head(2)

age  sex  steroid  antivirals fatigue malaise anorexia liver_big  \
0   30    1        0           1   False   False    False     False   
1   50    0        0           1    True   False    False     False   

  liver_firm spleen_palpable spiders ascites varices  bilirubin  \
0      False           False   False   False   False        1.0   
1      False           False   False   False   False        0.9   

   alk_phosphate  sgot  albumin    protime  histology  class  
0           85.0  18.0      4.0  61.852273          1      1  
1          135.0  42.0      3.5  61.852273          1      1

In [110]:
df3=df1.copy()

In [111]:
df3.head(2)

age  sex  steroid  antivirals fatigue malaise anorexia liver_big  \
0   30    1        0           1   False   False    False     False   
1   50    0        0           1    True   False    False     False   

  liver_firm spleen_palpable spiders ascites varices  bilirubin  \
0      False           False   False   False   False        1.0   
1      False           False   False   False   False        0.9   

   alk_phosphate  sgot  albumin    protime  histology  class  
0           85.0  18.0      4.0  61.852273          1      1  
1          135.0  42.0      3.5  61.852273          1      1

In [115]:
df3['fatigue']=pd.get_dummies(df3['fatigue'])
df3['malaise']=pd.get_dummies(df3['malaise'])
df3['anorexia']=pd.get_dummies(df3['anorexia'])
df3['liver_big']=pd.get_dummies(df3['liver_big'])
df3['liver_firm']=pd.get_dummies(df3['liver_firm'])
df3['spleen_palpable']=pd.get_dummies(df3['spleen_palpable'])
df3['spiders']=pd.get_dummies(df3['spiders'])
df3['ascites']=pd.get_dummies(df3['ascites'])
df3['varices']=pd.get_dummies(df3['varices'])

In [116]:
df3.head()

age  sex  steroid  antivirals  fatigue  malaise  anorexia  liver_big  \
0   30    1        0           1        0        1         1          0   
1   50    0        0           1        1        1         1          0   
2   78    0        1           1        1        1         1          1   
4   34    0        1           1        0        1         1          1   
5   34    0        1           1        0        1         1          1   

   liver_firm  spleen_palpable  spiders  ascites  varices  bilirubin  \
0           1                1        1        1        1        1.0   
1           1                1        1        1        1        0.9   
2           1                1        1        1        1        0.7   
4           1                1        1        1        1        1.0   
5           1                1        1        1        1        0.9   

   alk_phosphate   sgot  albumin    protime  histology  class  
0           85.0   18.0      4.0  61.852273          1      1  
1          135.0   42.0      3.5  61.852273          1      1  
2           96.0   32.0      4.0  61.852273          1      1  
4           85.0  200.0      4.0  61.852273          1      1  
5           95.0   28.0      4.0  75.000000          1      1

In [117]:
#split the dataframe into x and y variables
x=df3.drop('class', axis=1).values

In [118]:
y=df3['class'].values

In [133]:
#build a Machine Learning model
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.25, random_state=62)

In [134]:
from sklearn.linear_model import LogisticRegression

In [135]:
lr=LogisticRegression(solver='lbfgs')

In [136]:
lr.fit(x_train, y_train)

LogisticRegression()

In [137]:
y_pred=lr.predict(x_test)

In [138]:
y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1], dtype=int64)

In [176]:
accuracy_score(y_test, y_pred)

0.7948717948717948

In [139]:
from sklearn.metrics import confusion_matrix, classification_report

In [140]:
confusion_matrix(y_test, y_pred)

array([[ 3,  2],
       [ 6, 28]], dtype=int64)

In [141]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.33      0.60      0.43         5
           1       0.93      0.82      0.87        34

    accuracy                           0.79        39
   macro avg       0.63      0.71      0.65        39
weighted avg       0.86      0.79      0.82        39



In [143]:
from sklearn.neural_network import MLPClassifier

In [212]:
classifier= MLPClassifier(hidden_layer_sizes=(100,100), activation='relu', max_iter=10)

In [213]:
classifier.fit(x_train, y_train)

MLPClassifier(hidden_layer_sizes=(100, 100), max_iter=10)

In [214]:
y_pred1_nn= classifier.predict(x_test)

In [215]:
y_pred1_nn

array([0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [216]:
confusion_matrix(y_test, y_pred1_nn)

array([[ 3,  2],
       [ 4, 30]], dtype=int64)

In [217]:
from sklearn.metrics import accuracy_score

In [218]:
accuracy_score(y_test, y_pred1_nn)

0.8461538461538461

In [219]:
print(classification_report(y_test, y_pred1_nn))

              precision    recall  f1-score   support

           0       0.43      0.60      0.50         5
           1       0.94      0.88      0.91        34

    accuracy                           0.85        39
   macro avg       0.68      0.74      0.70        39
weighted avg       0.87      0.85      0.86        39

